# Generated by Django 3.2.7 on 2022-08-29 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.UUIDField(unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_nr', models.CharField(max_length=15, unique=True)),
                ('inside', models.BooleanField(default=False)),
                ('date_entered', models.DateTimeField(auto_now=True)),
                ('scans', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QrCodeId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('exit', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.participant')),
            ],
        ),
    ]
